app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

menu_presentation:
    path:     /menu/presentation
    defaults: { _controller: "AppBundle:Menu:presentation" }
    methods:  [GET, POST]

menu_avantage:
    path:     /menu/avantage
    defaults: { _controller: "AppBundle:Menu:avantage" }
    methods:  [GET, POST]

menu_contact:
    path:     /menu/contact
    defaults: { _controller: "AppBundle:Menu:contact" }
    methods:  [GET, POST]
